### PR TITLE
Reuse selector

### PR DESCRIPTION
**Pull request by omkar-334**
1.  Added Name & Location identifier to selector class.  
2. Added save & load methods for selector.  
3.  ``` compute subset selector``` function checks if selector exists. If not, it computes.  
4. Added tests for stofs 2s & 3d selectors.
5. Completed examples for stofs 2d & 3d (with reusing selectors)  
6.  Included subsetting for SWL and CWL with selector .  
7. Added ```open in colab``` links in example notebooks for convenience.   

Doubts
1. The selector is currently saved and loaded from current working directory. Should we use a separate folder like `cache` or `data`?  
2. The ```compute subset selector``` function checks for selector using the coordinates provided. If the user enters same coordinates but if the new dataset is a separate format (like schism vs adcirc), should we provide a parameter to override the check?  

@mpiannucci  @ChrisBarker-NOAA   
Can you check the selector code and examples for stofs-3d and 2d and let me know if any changes are needed?

### CODE REVIEW

**Comment by omkar-334** [comment]
Selector name is optional. If it is not specified, the default name is `selector_{location}.pkl`

**Comment by mpiannucci** [comment]
This all looks good except for adding the save and load methods. I would rather leave those methods out because I don't want to assume to know where the user is going to save the cached selectors. 

For example, if we are building a web service that runs in the cloud and returns a precomputed subset of the data, we would need to save and load the selector for S3 or other cloud object storage service, and the file path would definitely not lineup with those methods. 

If we want to keep the save and load methods, then we should allow users to optionally pass in an fsspec file system to do so, as well as a desired path they want to save to. 

At that point the only functionality we are abstracting is the pickling, so we could just make a save to bytes and load from bytes method instead that ensures the pickling process for saving and loading is reproducible

**Comment by omkar-334** [comment]
Hmm, I've changed the save & load methods to save to bytes and load from bytes. However this means I'll have to remove the `selector_exists` check in the `compute subset selector` method right?

**Comment by omkar-334** [comment]
image
You're right, the abstraction is only for the pickling and it's adding more complexity. Should we just remove the `save_from_bytes` and `load_from_bytes` methods?

**Comment by mpiannucci** [comment]
I think that the changes you have made here are good. While it is only abstracting away pickling, it is hiding that implementation detail from the user if we ever desired to change that detail in the future (even though that may be unlikely). I think the save and load from bytes methods are good, and they allow the most flexibility as long as we show examples how to use them with reading and writing to a file, or even better, reading or writing from cloud object storage.

I dont want to generatlize that this package will be used from notebooks, because i can foresee it being used to build APIs and other applications specific to different datasets in the future.

**Comment by omkar-334** [comment]
Ok got it, I will update the example notebooks to reflect the latest changes.

**Pull request merged**
