### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by omkar-334**
[Docs](https://xarray-subset-grid.readthedocs.io/en/latest/)  
I've added auto-docstring documentation and embedded our example ipynb notebooks too. Let me know what you think.
Also, I've changed the location of `examples` into `docs` now.

### CODE REVIEW

**Comment by omkar-334** [comment]
I've disabled the notebook execution, so it just renders the available output instead of executing it each build.

**Comment by mpiannucci** [comment]
Awesome Job, this is perfect! How are these deployed and can w have them deployed via github actions somehow?

**Comment by omkar-334** [comment]
It's deployed through https://readthedocs.com/ and once its set up, it gets built after every commit automatically.

**Comment by mpiannucci** [comment]
Great!!

**Pull request merged**
